name: github-actions-practice # name of the workflow 
on: workflow_dispatch # trigger on which event 
jobs:
  checkker:
  runs-on: ubnutu-latest 
  steps:
    - name: checkout the html code # this the name of the step 
      uses: actions/checkout # this step is using a actions that is why uses 
    - name: context object overview
      run: "echo ${{toJSON(github)}}" # runnning some command. 
