name: github-actions-practice # name of the workflow 
on: 
 push: # trigger on which event 
   branches:
       - main
       - 'dev-*'
       - 'IPR-*'
 pull_request: # evvent with activity_types. 
       types:
         - opened # types will named as past tense -> opened , closed , created , edited 
 workflow_dispatch:  
jobs:
  checkker:
   runs-on: ubuntu-latest 
   steps:
    - name: checkout the html code # this the name of the step 
      uses: actions/checkout@v6  # this step is using a actions that is why uses 
    - name: context object overview
      run: echo "${{toJSON(github)}}" # runnning some command. 
    - name: uploading raw data to artifacts 
      uses: actions/upload-artifact@v7 
      with:
        name: html-code # writng '|' in yaml meanse writng single line to multiple , that eveything below it will become like  / dist/json/newfile   
        path: |
           index.html 
  Uploader_Job:
    needs: checkker # needs - to make the job dependable on another ( v.imp key concept) || to ~
    runs-on: ubuntu-latest
    steps:
      - name: download the artifacts
        uses: actions/download-artifact@v8
        with:
          name: html-code
      



# nothing will be started with : -> it will always be used in end ":"

