name: github-actions-practice # name of the workflow 
on: 
 push: # trigger on which event 
   branches:
       - main
       - 'dev-*'
       - 'IPR-*'
 pull_request: # evvent with activity_types. 
       types:
         - opened # types will named as past tense -> opened , closed , created , edited 
 workflow_dispatch:  
env:
  Name: "Agam Bajaj"
jobs:
  checkker:
   runs-on: ubuntu-latest 
   environment: testing # this is environment to access secrets 
   outputs: 
     main-key: ${{ steps.output_generator.outputs.key }} # learning steps.id.outputs.key ( in $GITHUB_OUTPUT the key value pair are arranged like {outputs:{ key1:value1 , key2:value2 , key3:value3}} )
   steps:
    - name: checkout the html code # this the name of the step 
      uses: actions/checkout@v6  # this step is using a actions that is why uses 
    - name: catcheing implemetnation 
      uses: actions/catche@v6
      with:
        path: |
           index.html
        key: ${{ hashFiles('index.html')}}
    - name: context object overview
      run: echo "${{toJSON(github)}}" # runnning some command. 
    - name: uploading raw data to artifacts 
      uses: actions/upload-artifact@v7 
      with:
        name: html-code # writng '|' in yaml meanse writng single line to multiple , that eveything below it will become like  / dist/json/newfile   
        path: |
           index.html 
    - name: setitng up output and showing it 
      id: output_generator  
      run: echo "key=helloworld" >> "$GITHUB_OUTPUT"  # a context variable that store key=value pair. 
    - name: output of GITHUB_OUTPUT
      run: cat $GITHUB_OUTPUT
  Uploader_Job:
    needs: checkker # needs - to make the job dependable on another ( v.imp key concept) || to ~
    runs-on: ubuntu-latest
    steps:
      - name: ustilizin my secrets of ${{env.Name}}
        run: echo "${{secrets.MONGO_DB_USERNAME}}"
      - name: let you know my password
        run: echo "${{secrets.MONGO_DB_PASSWORD}}"
      - name: download the artifacts
        uses: actions/download-artifact@v8
        with:
          name: html-code
      - name: using outputs from checkker 
        run: echo "${{needs.checkker.outputs.main-key}}"
      



# nothing will be started with : -> it will always be used in end ":"

